name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Vet
        run: |
          gofmt -l . | tee fmt.log
          if [ -s fmt.log ]; then
            echo "gofmt found changes" && exit 1
          fi
          go vet ./...
      - name: Test
        env:
          CGO_ENABLED: 0
        run: |
          go test -race -cover ./...
