name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
        run: |
          VERSION=${GITHUB_REF##*/}
          DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          COMMIT=${GITHUB_SHA}
          PACKAGE=ooxmlx_${VERSION#v}_${{ matrix.goos }}_${{ matrix.goarch }}
          BINARY=${PACKAGE}
          if [ "${{ matrix.goos }}" = "windows" ]; then
            BINARY=${BINARY}.exe
          fi
          go build -ldflags "-s -w -X github.com/example/ooxmlx/internal/buildinfo.Version=${VERSION#v} -X github.com/example/ooxmlx/internal/buildinfo.Commit=${COMMIT} -X github.com/example/ooxmlx/internal/buildinfo.Date=${DATE}" -o ${BINARY} ./cmd/ooxmlx
          zip -j ${PACKAGE}.zip ${BINARY}
          rm -f ${BINARY}
          shasum -a 256 ${PACKAGE}.zip > SHA256SUMS.txt
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.goos }}-${{ matrix.goarch }}
          path: |
            *.zip
            SHA256SUMS.txt

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
      - name: Combine checksums
        run: |
          find dist -name 'SHA256SUMS.txt' -exec cat {} + > SHA256SUMS.txt
      - name: Gather assets
        run: |
          mkdir upload
          find dist -name '*.zip' -exec cp {} upload/ \;
          cp SHA256SUMS.txt upload/
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: upload/*
